// Events the glue UI listens for. The names are Blizzard's - GlueParent.lua,
// AccountLogin.lua, RealmList.lua and CharacterSelect.lua register these exact strings,
// so they are the contract between our networking and their Lua.
enum EventType {
  FRAMES_LOADED = 'FRAMES_LOADED',
  SET_GLUE_SCREEN = 'SET_GLUE_SCREEN',

  // Login progress dialog
  OPEN_STATUS_DIALOG = 'OPEN_STATUS_DIALOG',
  UPDATE_STATUS_DIALOG = 'UPDATE_STATUS_DIALOG',
  CLOSE_STATUS_DIALOG = 'CLOSE_STATUS_DIALOG',

  // Realm selection
  OPEN_REALM_LIST = 'OPEN_REALM_LIST',
  GET_PREFERRED_REALM_INFO = 'GET_PREFERRED_REALM_INFO',
  SUGGEST_REALM = 'SUGGEST_REALM',
  SERVER_SPLIT_NOTICE = 'SERVER_SPLIT_NOTICE',
  SHOW_SERVER_ALERT = 'SHOW_SERVER_ALERT',

  // Character selection
  CHARACTER_LIST_UPDATE = 'CHARACTER_LIST_UPDATE',
  UPDATE_SELECTED_CHARACTER = 'UPDATE_SELECTED_CHARACTER',
  SELECT_FIRST_CHARACTER = 'SELECT_FIRST_CHARACTER',
  SELECT_LAST_CHARACTER = 'SELECT_LAST_CHARACTER',
  FORCE_RENAME_CHARACTER = 'FORCE_RENAME_CHARACTER',

  // Session
  DISCONNECTED_FROM_SERVER = 'DISCONNECTED_FROM_SERVER',
  CLIENT_ACCOUNT_MISMATCH = 'CLIENT_ACCOUNT_MISMATCH',
  CLIENT_TRIAL = 'CLIENT_TRIAL',
  PLAYER_ENTER_TOKEN = 'PLAYER_ENTER_TOKEN',
  GAME_ACCOUNTS_UPDATED = 'GAME_ACCOUNTS_UPDATED',

  // Addons, sound, misc
  ADDON_LIST_UPDATE = 'ADDON_LIST_UPDATE',
  START_GLUE_MUSIC = 'START_GLUE_MUSIC',
  SCANDLL_ERROR = 'SCANDLL_ERROR',
  SCANDLL_FINISHED = 'SCANDLL_FINISHED',
  SHOW_SURVEY_NOTIFICATION = 'SHOW_SURVEY_NOTIFICATION',
  ACCOUNT_MESSAGES_AVAILABLE = 'ACCOUNT_MESSAGES_AVAILABLE',
  ACCOUNT_MESSAGES_BODY_LOADED = 'ACCOUNT_MESSAGES_BODY_LOADED',
  ACCOUNT_MESSAGES_HEADERS_LOADED = 'ACCOUNT_MESSAGES_HEADERS_LOADED',
}

export default EventType;
