// Regenerates src/net/world/opcodes.ts from AzerothCore's Opcodes.h.
//
//   node tools/codegen/opcodes.mjs [path/to/azerothcore-wotlk]
//
// There are ~1300 opcodes; typing them by hand would be both tedious and a source of
// silent one-character errors.

import fs from 'node:fs';
import path from 'node:path';

const root = process.argv[2] ?? '../azerothcore-wotlk';
const source = path.join(root, 'src/server/game/Server/Protocol/Opcodes.h');
const target = 'src/net/world/opcodes.ts';

const header = fs.readFileSync(source, 'utf8');

const entries = [];
const seen = new Map();
const pattern = /^\s+((?:CMSG|SMSG|MSG)_\w+)\s*=\s*(0x[0-9A-Fa-f]+)/gm;

let match;
while ((match = pattern.exec(header)) !== null) {
  const [, name, value] = match;
  const code = parseInt(value, 16);
  // A handful of names are aliases for the same code. TypeScript enums allow that, but
  // reverse lookup then depends on declaration order, so keep the first and note the rest.
  if (seen.has(name)) {
    continue;
  }
  seen.set(name, code);
  entries.push({ name, code });
}

if (entries.length === 0) {
  throw new Error(`no opcodes found in ${source}`);
}

const numMsgTypes = /NUM_MSG_TYPES\s*=\s*(0x[0-9A-Fa-f]+)/.exec(header)?.[1] ?? '0x521';

const lines = entries.map(({ name, code }) => `  ${name} = 0x${code.toString(16).toUpperCase().padStart(3, '0')},`);

const byCode = new Map();
for (const { name, code } of entries) {
  if (!byCode.has(code)) {
    byCode.set(code, name);
  }
}

fs.mkdirSync(path.dirname(target), { recursive: true });
fs.writeFileSync(
  target,
  `// Generated by tools/codegen/opcodes.mjs from AzerothCore's
// src/server/game/Server/Protocol/Opcodes.h. Do not edit by hand.
//
// ${entries.length} opcodes, 3.3.5a / build 12340.

export enum Opcode {
${lines.join('\n')}
}

/** The server drops the connection for any opcode at or above this. */
export const NUM_MSG_TYPES = ${numMsgTypes};

const NAMES: Record<number, string> = {
${[...byCode.entries()].map(([code, name]) => `  ${code}: '${name}',`).join('\n')}
};

export const opcodeName = (opcode: number): string =>
  NAMES[opcode] ?? \`UNKNOWN_0x\${opcode.toString(16).toUpperCase().padStart(3, '0')}\`;
`,
);

console.log(`wrote ${target}: ${entries.length} opcodes (NUM_MSG_TYPES ${numMsgTypes})`);
